Wyooming/Controllers/ContactsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Wyooming.Data;
using Wyooming.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Wyooming.Authorization;

namespace Wyooming.Controllers
{
    public class ContactsController : Controller
    {
        private readonly WyoomingContext _context;
        private readonly IAuthorizationService _authorizationService;
        private readonly UserManager<ApplicationUser> _userManager;

        public ContactsController(WyoomingContext context, 
            IAuthorizationService authorizationService,
            UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
            _authorizationService = authorizationService;
        }

        // GET: Contacts
        public async Task<IActionResult> Index()
        {
            return View(await _context.Contact.ToListAsync());
        }

        // GET: Contacts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contact = await _context.Contact
                .SingleOrDefaultAsync(m => m.ContactId == id);
            if (contact == null)
            {
                return NotFound();
            }

            return View(contact);
        }

        // GET: Contacts/Create
        public IActionResult Create()
        {

            return View();
        }



        // POST: Contacts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ContactEditViewModel editModel)
        {
            if (!ModelState.IsValid)
            {
                return View(editModel);
                
            }

            var contact = ViewModel_to_model(new Contact(), editModel);
            contact.OwnerID = _userManager.GetUserId(User);

            var isAuthorized = await _authorizationService.AuthorizeAsync(User, contact, ContactOperations.Create);

            if (!isAuthorized)
            {
                return new ChallengeResult();
            }

            _context.Add(contact);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        // GET: Contacts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contact = await _context.Contact.SingleOrDefaultAsync(m => m.ContactId == id);
            if (contact == null)
            {
                return NotFound();
            }
            var isAuthorized = await _authorizationService.AuthorizeAsync(User, contact, ContactOperations.Update);

            if (!isAuthorized)
            {
                return new ChallengeResult();
            }
                
            var editModel = Model_to_viewModel(contact);

            return View(editModel);
        }

        // POST: Contacts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, ContactEditViewModel editModel)
        {
            if (!ModelState.IsValid)
            {
                return View(editModel);
            }
            var contact = await _context.Contact.SingleOrDefaultAsync(m => m.ContactId == id);
            if (contact == null)
            {
                return NotFound();
            }
            var isAuthorized = await _authorizationService.AuthorizeAsync(User, contact, ContactOperations.Update);

            if (!isAuthorized)
            {
                return new ChallengeResult();
            }

            contact = ViewModel_to_model(contact, editModel);
            if (contact.Status == ContactStatus.Approved)
            {
                var canApprove = await _authorizationService.AuthorizeAsync(User, contact, ContactOperations.Approve);

                if (!canApprove)
                {
                    contact.Status = ContactStatus.Submitted;
                }
            }

            _context.Update(contact);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }

        // GET: Contacts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contact = await _context.Contact
                .SingleOrDefaultAsync(m => m.ContactId == id);
            if (contact == null)
            {
                return NotFound();
            }

            var isAuthorized = await _authorizationService.AuthorizeAsync(User, contact,
                                ContactOperations.Delete);
            if (!isAuthorized)
            {
                return new ChallengeResult();
            }

            return View(contact);
        }

        // POST: Contacts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var contact = await _context.Contact.SingleOrDefaultAsync(m => m.ContactId == id);

            var isAuthorized = await _authorizationService.AuthorizeAsync(User, contact,
                                        ContactOperations.Delete);
            if (!isAuthorized)
            {
                return new ChallengeResult();
            }

            _context.Contact.Remove(contact);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private Contact ViewModel_to_model(Contact contact, ContactEditViewModel editModel)
        {
            contact.Address = editModel.Address;
            contact.City = editModel.City;
            contact.Email = editModel.Email;
            contact.Name = editModel.Name;
            contact.State = editModel.State;
            contact.Zip = editModel.Zip;

            return contact;
        }

        private ContactEditViewModel Model_to_viewModel(Contact contact)
        {
            var editModel = new ContactEditViewModel();

            editModel.ContactId = contact.ContactId;
            editModel.Address = contact.Address;
            editModel.City = contact.City;
            editModel.Email = contact.Email;
            editModel.Name = contact.Name;
            editModel.State = contact.State;
            editModel.Zip = contact.Zip;

            return editModel;
        }

        private bool ContactExists(int id)
        {
            return _context.Contact.Any(e => e.ContactId == id);
        }
    }
}

Wyooming/Views/Shared/_Layout.cshtml
@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css">
    <link rel="stylesheet" href="~/css/ionicons.css">

   
</head>
<body>
    
    <header class="header">
        <div class="headerContent">
            <div class="headerColumns">
                <div class="logo">
                    <a asp-controller="home" asp-action="Index"><img src="~/images/logo.png" width="76px" /></a>
                </div>
                <div class="topHeader">
                    <div class="welcomLogin">
                        <i class="icon ion-android-lock"></i> <label>Welcome to our Shop, <a asp-action="Login" asp-controller="Account"> Login</a></label>
                    </div>
                    <div class="register">
                        <i class="icon ion-android-person"></i> <label><a asp-controller="Account" asp-action="Register"> Register</a></label>
                    </div>
                    <div class="giftCart">
                        <i class="icon ion-card"></i> <label><a href="#"> Gift Card</a></label>
                    </div>
                </div>
                <div class="searchHeader">
                    <div class="CartHeaderDiv">
                        <a href="#"><i style="margin-right: 10px" class="icon ion-android-cart"></i>  Show Cart <label>0</label> </a>
                    </div>
                    <div class="SearchTool">
                        <form>
                            <input type="text" placeholder="Search your Procuct, Brand or ..." />
                            <button type="submit" class="searchIcon"><i class="icon ion-android-search "></i></button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="headerMenus">
            <div class="MenuItems">
                <nav>
                    <a class="MenuItem" href="#">Digital Products<i class="icon ion-ios-arrow-down"></i></a>
                    <a class="MenuItem" href="#">Home Furniture<i class="icon ion-ios-arrow-down"></i></a>
                    <a class="MenuItem" href="#">Health & Beauty<i class="icon ion-ios-arrow-down"></i></a>
                    <a class="MenuItem" href="#">Sports & Entertainment<i class="icon ion-ios-arrow-down"></i></a>
                    <a class="MenuItem" href="#">Tools<i class="icon ion-ios-arrow-down"></i></a>
                    <a class="MenuItem" href="#">Arts and Culture<i class="icon ion-ios-arrow-down"></i></a>
                </nav>
            </div>
        </div>

    </header>

        @RenderBody()
        

    <footer>

        <div class="footerUpperContent">
            <div class="footerContent">
                <label>24 Hours of the day, 7 days of the week, waiting for your call...</label>
                <label>info@medialight.se</label>
                <label style="float: right;">www.medialight.se</label>
            </div>
        </div>
        <div class="footerMiddleContent">
            <div class="footerContent">
                <a asp-controller="Contacts" asp-action="Index" class="navbar-nav" >Contacts List</a>
            </div>
        </div>

    </footer>

    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/js/site.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>